import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Nav from "@/components/navbar/nav";
import ReduxProvider from "@/redux/storeProvider";
import Provider from "@/components/auth/Provider";
import Footer from "@/components/custom-ui/Footer";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="scroll-thin">
      <body
      >
        <AppRouterCacheProvider>
          <Provider>
            <ReduxProvider>
              <Nav />
              {children}
              <Footer />
            </ReduxProvider>
          </Provider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
